files:
  - source: /**/*.md
    translation: /docs/%locale_with_underscore%/%original_path%/%original_file_name%
    languages_mapping:
      locale_with_underscore:
        zh-CN: zh-hans
  - source: /**/*.png
    translation: /docs/%locale_with_underscore%/%original_path%/%original_file_name%
    languages_mapping:
      locale_with_underscore:
        zh-CN: zh-hans
